### ISSUE TITLE
Hi All,

### ISSUE THREAD

**Issue by amarnath552** [probot/smee-client#189]
Hi All,

I am trying to use Smee client to trigged the Job in Jenkins from git webhook. I created the new job in Jenkins and commit any change in the git, I am able to triggered the Job in Jenkins. When I tried to made any change in the git 2nd time, smee getting the response from git but job not triggered in the Jenkins. If removed the 1st build in the Jenkins and commit the changes in git it's working. 
smee --url https://smee.io/XXXXXxxxxxxx --target http://127.0.0.1:8080/github-webhook/
 Finally if I removed all the builds on the job,then only new build triggered.

Can  any one please suggest or provide any solution on this issue.

**Comment by tcbyrd** [comment]
Hey there @amarnath552! I'm afraid the smee maintainers aren't that familiar with the Jenkins side of this. In general this sounds like it may be related to the `github-webhook` handler ignoring the webhook when there's a build in progress? If it were me I'd try to see if I can debug what happens when I send the payload to `/github-webhook` multiple times without Smee, just to rule out if it's Smee that's the problem or just the Jenkins side.
